BEGIN;
INSERT INTO genre (genreID, genreName) VALUES
(0, 'Fantasy'),
(1, 'SciFi'),
(2, 'Romance'),
(3, 'Horror'),
(4, 'Mystery'),
(5, 'Drama'),
(6, 'Comedy'),
(7, 'Adventure'),
(8, 'Nonfiction'),
(9, 'Religion'),
(10, 'Reference'),
(11, 'RockNRoll'),
(12, 'HipHop'),
(13, 'Rap'),
(14, 'Blues'),
(15, 'Raggea'),
(16, 'Pop'),
(17, 'Punk'),
(18, 'Metal'),
(19, 'Gospel'),
(20, 'Polka'),
(21, 'Swing'),
(22, 'Orchestral'),
(23, 'Jazz'),
(24, 'Bluegrass'),
(25, 'AudioBook'),
(26, 'Documentary'),(27, 'Country')
;